# This workflow will do a clean installation of node dependencies, cache/restore them, build the project, and deploy to test

name: deploy_to_test

on:
    push:
        branches: ['dev']

jobs:
    deploy:
        runs-on: ubuntu-latest

        env:
            APP_KEY: ${{ secrets.TEST_APP_KEY }}

        strategy:
            matrix:
                node-version: [18.x, 20.x]

        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'npm'
            - run: npm ci
            - run: npm run build --if-present
            - run: npm test
